### ISSUE TITLE
basePath configuration does not work when deploying to Vercel

### ISSUE THREAD

**Issue by timuster** [styxlab/next-cms-ghost#68] opened 2021-04-03 07:12 UTC
I tried using the `basePath` option in `next.config.js`, but deploying to Vercel fails with the error below.

**How to reproduce**
1. git clone a fresh copy of this repository
2. update `next.config.js` and add ` basePath: '/pages',` (I added mine right after `reactStrictMode: true,`)
3. Run `vercel` from the terminal and try deploying to a new project

Vercel will throw the following error:

```
Error! ENOENT: no such file or directory, open '/vercel/workpath0/.next/server/pages/pages/404.html'
```

Checking the logs sheds some more light:

```
$vercel logs [my project]



2021-04-03T07:05:04.325Z  ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
2021-04-03T07:05:04.325Z     (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
2021-04-03T07:05:04.325Z


2021-04-03T07:05:04.547Z  $ next-sitemap
2021-04-03T07:05:04.649Z  Done in 56.12s.
2021-04-03T07:05:21.917Z  Traced Next.js server files in: 17230.042ms
2021-04-03T07:05:23.957Z  [Error: ENOENT: no such file or directory, open '/vercel/workpath0/.next/server/pages/pages/404.html'] {
2021-04-03T07:05:23.957Z    errno: -2,
2021-04-03T07:05:23.957Z    code: 'ENOENT',
2021-04-03T07:05:23.958Z    syscall: 'open',
2021-04-03T07:05:23.958Z    path: '/vercel/workpath0/.next/server/pages/pages/404.html'
2021-04-03T07:05:23.958Z  } {
2021-04-03T07:05:23.958Z    file: FileFsRef {
2021-04-03T07:05:23.958Z      type: 'FileFsRef',
2021-04-03T07:05:23.958Z      mode: 33188,
2021-04-03T07:05:23.958Z      contentType: undefined,
2021-04-03T07:05:23.959Z      fsPath: '/vercel/workpath0/.next/server/pages/pages/404.html'
2021-04-03T07:05:23.959Z    },
2021-04-03T07:05:23.959Z    fileName: '.next/server/pages/pages/404.html'
2021-04-03T07:05:23.959Z  }
2021-04-03T07:05:23.960Z  [Error: ENOENT: no such file or directory, open '/vercel/workpath0/.next/server/pages/pages/404.html'] {
2021-04-03T07:05:23.960Z    errno: -2,
2021-04-03T07:05:23.960Z    code: 'ENOENT',
2021-04-03T07:05:23.960Z    syscall: 'open',
2021-04-03T07:05:23.960Z    path: '/vercel/workpath0/.next/server/pages/pages/404.html'
2021-04-03T07:05:23.960Z  }

```

**Comment by timuster** [comment] 2021-04-03 07:23
I thought there was perhaps something wrong with `next-sitemap` (on the post build step). However, the deployment fails even after I remove the `postbuild` step from package.json.

**Comment by styxlab** [comment] 2021-04-03 08:06
@timuster Welcome to this project! Could you please test the 'basePath' option with another name, eg 'blog' instead of 'page'? In addition, please publish your 'next.config' here.

**Comment by timuster** [comment] 2021-04-03 08:53
@styxlab Thank you for the project! It's one of the best Ghost starters I've come across! :) 

I get the same problem with `/blog` instead of `/pages`. 

I think the problem is somewhere in 404.tsx - the deployment succeeds if I delete that file or replace its content with a simpler version.

For example, replacing the content of 404.tsx to the following works:

```
export default function My404() {
    return (<h1>404</h1>)
}
```

Here's my `next.config.js` by the way:

```
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true',
})

module.exports = withBundleAnalyzer({
  ...(process.env.NETLIFY === 'true' && { target: 'serverless' }),
  basePath: '/blog',
  images: {
    deviceSizes: [320, 500, 680, 1040, 2080, 2048, 3120],
    domains: [
      'localhost',
      'images.unsplash.com',
      'static.gotsby.org',
      'static.ghost.org',
      'hooshmand.net',
      'cms.jamify.org',
      'demo.jamify.org',
      'www.jamify.org',
      'www.gatsbyjs.org',
      'cdn.commento.io',
      'gatsby.ghost.io',
      'ghost.org',
      'repository-images.githubusercontent.com',
      'www.gravatar.com',
      'github.githubassets.com',
      'www.crio.do',
      'drive.google.com',
      'lh3.googleusercontent.com',
      'lh6.googleusercontent.com',
    ],
  },
  reactStrictMode: true,
})

```

**Comment by styxlab** [comment] 2021-04-03 09:36
Thanks for the heads up 😊 and your analysis! I will look closer into the custom 404.tsx and see if the problem can be fixed.

**Comment by styxlab** [comment] 2021-04-06 07:16
@all-contributors please add @timuster for bug

**Comment by styxlab** [comment] 2021-04-06 09:19
Able to reproduce the error on Vercel. In order to run into the issue the following conditions must be fulfilled:

1. use `basePath` option
2. `getStaticProps()` within 404.tsx (which is currently the case for this repo)
3. Deploy to Vercel => build error (local building works).

This looks like a bug with Next.js/ Vercel which needs to be solved upstream. I will make a toy example and submit a bug report to Next.js.

In the meantime, please replace 404.tsx with a simplified versions (without `getStaticProps`) if you run into this issue as suggested by @timuster above.

**Comment by styxlab** [comment] 2021-04-06 09:53
https://github.com/vercel/vercel/issues/6073

**Comment by styxlab** [comment] 2021-04-29 21:02
This issue has been fixed in the latest Next.js 10.2.0. @timuster: Please redeploy and report back.

**Comment by styxlab** [comment] 2021-05-01 08:57
Closing as solved upstream.

**Closed by styxlab** 2021-05-01 08:57 UTC
