### ISSUE TITLE
Deploying on Vercel results in 404 for index page

### ISSUE THREAD

**Issue by simhol** [styxlab/next-cms-ghost#74] opened 2021-04-17 12:50 UTC
Deploying to Vercel works pretty nice in general.

However, I have an issue right not that my site (https://thesmartcoder.dev) is showing a 404 page on the index route on Vercel. If you click on Go to the front page → though, the site loads correctly. I've tested in Chrome, Firefox, and on Mobile so far. A new deployment fixes this issue but only for some random amount of time. The internal vercel URL does work though, so maybe it's something with domain resolution and I have to contact Vercel directly? Strange....

**Comment by styxlab** [comment] 2021-04-17 13:11
That's definitely a strange issue and points towards some domain configuration or caching issue on Vercel. You'll have to talk to Vercel support to sort this one out.

**Comment by styxlab** [comment] 2021-04-17 18:52
What you could do in order to isolate the issue (one change at a time):

1. Switch off ISR (change to  `false`): https://github.com/styxlab/next-cms-ghost/blob/03992396dbc26395d93b1b8533166b827c275ed8/appConfig.ts#L52
2. Remove the [custom 404 page](https://github.com/styxlab/next-cms-ghost/blob/master/pages/404.tsx) (so the simpler, internal 404 page kicks in)

If the issue disappears you at least know where to look further. I also have another open 404 issue with Vercel (see #68), but in this case the build process fails entirely.

**Comment by styxlab** [comment] 2021-04-18 15:21
Did you find the root cause?

**Comment by styxlab** [comment] 2021-04-21 06:28
This does not seem tp be fixed... Still investigating....

**Comment by mbernard** [comment] 2021-04-21 11:39
I got the same error yesterday. I redeployed and it worked, but that seem to be a temporary fix

**Comment by styxlab** [comment] 2021-04-21 13:06
@mbernard: Thanks for sharing. Apparently a fresh redeploy fixes it for a couple of days until the issue re-occurs. These type of flaky issues are really hard to debug and the root cause is most likely somewhere in the Vercel infrastructure. My hunch is that it has to do with the custom 404 page, so it might be worth checking if removing the 404.tsx from the `pages` folder "fixes" the issue.

**Comment by styxlab** [comment] 2021-04-22 11:46
Opened https://github.com/vercel/vercel/issues/6135 upstream.

**Comment by styxlab** [comment] 2021-04-22 12:13
@mbernard & @simhol : Could you please test, if the issue is also present on your Vercel *.app domains that are automatically assigned to your project?

**Comment by styxlab** [comment] 2021-04-23 22:09
According to Vercel support this issue has been fixed! For the fix to take affect, you have to set the environment variable below:

```
FORCE_RUNTIME_TAG=canary
```

and redeploy your project. I got no further information about the root cause.

**Comment by styxlab** [comment] 2021-04-24 07:01
Update from Vercel support:

The change has been made available on stable now, so there is **there's no need for the runtime tag anymore**. The issue was a Next.js bug with indexing a catch-all page in combination with a number of other circumstances.

**Comment by styxlab** [comment] 2021-04-27 09:28
Monitored [next.jamify.org](https://next.jamify.org) for 3 days and the issue did not re-appear.

**Closed by styxlab** 2021-04-27 09:28 UTC

**Comment by mattfreire** [comment] 2021-07-19 17:54
I've had the issue lately as well. Seems adding the environment variable was the only way to get it to work. Thanks!

**Comment by Mnigos** [comment] 2021-12-21 12:50
I've got the issue right now and adding the environment variable doesn't work for me. ;/

**Comment by styxlab** [comment] 2021-12-21 14:15
If it doesn't go away after a re-deploy, you are seeing a different issue. 

Make sure you update to the latest version of this repo and  re-deploy. If this still does not work, please create a new issue, describe the steps leading to the issue and also link to your example repo for further debugging.
