### ISSUE TITLE
Running with Node 16 on ARM M1 causes SIGSEGV

### ISSUE THREAD

**Issue by raihanameen** [styxlab/next-cms-ghost#88] opened 2021-05-23 12:40 UTC
Even after closely following the readme, I couldn't get the project to run in both the local environment as well as in a docker container.

The console output while running inside a container is below:

> node ➜ /workspaces/ghost-blog (master ✗) $ yarn
> yarn install v1.22.5
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> info fsevents@2.3.2: The platform "linux" is incompatible with this module.
> info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
> [3/4] Linking dependencies...
> [4/4] Building fresh packages...
> Done in 67.42s.

> node ➜ /workspaces/ghost-blog (master ✗) $ yarn dev
> yarn run v1.22.5
> $ next dev
> ready - started server on 0.0.0.0:3000, url: http://localhost:3000
> info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
> event - compiled successfully
> Attention: Next.js now collects completely anonymous telemetry regarding usage.
> This information is used to shape Next.js' roadmap and prioritize features.
> You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
> https://nextjs.org/telemetry
> 
> event - build page: /
> wait  - compiling...
> event - build page: /404
> event - compiled successfully
> Killed
> error Command failed with exit code 137.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> node ➜ /workspaces/ghost-blog (master ✗) $ 

In local I also got this error:
> error Command failed with signal "SIGSEGV".

**Comment by styxlab** [comment] 2021-05-23 12:51
Welcome @raihanameen! I can't give any support for docker builds, but a regular build on `localhost` should work without any issues.

Please start over with the following steps and report the outputs

OS/tool versions:
1. uname -a
2. node -v
3. yarn -v
4. git --version

Build example project:
1. git clone https://github.com/styxlab/next-cms-ghost.git
2. cd next-cms-ghost
3. yarn
4. yarn build

**Comment by raihanameen** [comment] 2021-05-23 14:11
I tried it again from scratch in my local workspace but I am having issues. I also tried with the latest releases 1.4.1 and 1.4.0 and still the same issue. I'm not sure if it is specific to my hardware.

I use an Apple Macbook Air with the recently released M1 chip and 16GB Unified Memory.

My tools and versions are:

<img width="1042" alt="Screenshot 2021-05-23 at 7 38 48 PM" src="https://user-images.githubusercontent.com/36153203/119263888-8b6a0300-bbfe-11eb-9dea-ac484e77fd30.png">

**Comment by styxlab** [comment] 2021-05-23 15:18
What's the output of 'yarn build' ?

**Comment by raihanameen** [comment] 2021-05-23 15:21
build is successful but the error occurs while running it. I checked for both dev and prod build, but still no luck.

**Comment by styxlab** [comment] 2021-05-23 15:52
I never tried Node v16, that could be an issue. Are you able to run the Next.js standard example?

**Comment by raihanameen** [comment] 2021-05-23 15:57
Yes, I tried the below example and it worked perfectly fine.

`
yarn create next-app --example blog-starter-typescript blog-starter-typescript-app
`

**Comment by styxlab** [comment] 2021-05-23 19:12
Hmm,137 generally means an Out of memory type state where Node.js crashes. Would be happy to look into it further, but I do not know how to reproduce this without having the exact Apple machine at my disposal. Maybe there is one dependency that is incompatible with your machine / OS / CPU.

Next steps would be to connect a debugger to your session (https://nextjs.org/docs/advanced-features/debugging), but am not sure how much time you want to spend on this.

I suggest you use the "Vercel" or "Netlify" buttons in the README to test out if the repo to see if it fits your needs and defer debugging localhost to a later time.

**Comment by styxlab** [comment] 2021-05-26 21:04
Closing as I cannot reproduce the issue. Let me know if you have more info, so it makes sense to re-open it.

**Comment by raihanameen** [comment] 2021-05-26 21:39
## Hi sorry for delay but I ran the application in debug mode following the link you gave above and below is the error I got in google chrome's console

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
log.ts:29 info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
log.ts:33 event - compiled successfully
DevTools failed to load SourceMap: Could not load content for file:///Users/raihanameen/Downloads/GitHub/next-cms-ghost/node_modules/next/dist/compiled/path-to-regexp/index.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load SourceMap: Could not load content for file:///Users/raihanameen/Downloads/GitHub/next-cms-ghost/node_modules/next/dist/compiled/regexr-lexer/lexer.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load SourceMap: Could not load content for file:///Users/raihanameen/Downloads/GitHub/next-cms-ghost/node_modules/next/dist/compiled/regexr-lexer/profiles.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load SourceMap: Could not load content for file:///Users/raihanameen/Downloads/GitHub/next-cms-ghost/node_modules/@next/react-refresh-utils/ReactRefreshWebpackPlugin.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load SourceMap: Could not load content for file:///Users/raihanameen/Downloads/GitHub/next-cms-ghost/node_modules/typescript/lib/typescript.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load SourceMap: Could not load content for file:///Users/raihanameen/Downloads/GitHub/next-cms-ghost/node_modules/postcss-custom-media/index.cjs.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load SourceMap: Could not load content for file:///Users/raihanameen/Downloads/GitHub/next-cms-ghost/node_modules/postcss-nesting/index.cjs.js.map: System error: net::ERR_FILE_NOT_FOUND
log.ts:33 event - build page: /404
log.ts:13 wait  - compiling...
DevTools failed to load SourceMap: Could not load content for file:///Users/raihanameen/Downloads/GitHub/next-cms-ghost/node_modules/@next/react-refresh-utils/loader.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load SourceMap: Could not load content for file:///Users/raihanameen/Downloads/GitHub/next-cms-ghost/node_modules/@next/react-refresh-utils/internal/ReactRefreshModule.runtime.js.map: System error: net::ERR_FILE_NOT_FOUND
log.ts:33 event - compiled successfully
log.ts:33 event - build page: /
log.ts:13 wait  - compiling...
log.ts:33 event - compiled successfully


## Below is the console log 

```
❯ yarn demo
yarn run v1.22.10
$ NODE_OPTIONS='--inspect' next dev
Debugger listening on ws://127.0.0.1:9229/c589253e-8172-4944-b726-bc6b5d6eccd8
For help, see: https://nodejs.org/en/docs/inspector
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
event - compiled successfully
Debugger attached.
event - build page: /404
wait  - compiling...
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
error Command failed with signal "SIGSEGV".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## And I also ran using the vscode debugger with .vscode/launch.json and I got the error mentioned below:

Error processing attach: Error: Could not connect to debug target at http://localhost:9229: Promise was canceled
at e (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:1:118713)
at t (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:59:46042)
at C.launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:1:142346)
at t.Binder.captureLaunch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:59:179274)
at t.Binder._launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:59:178825)
at async Promise.all (index 5)
at t.Binder._boot (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:59:178085)
at t.default._onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:1:91852)

> I have tried this application in different cloud platforms like heroku, and vercel and there it was successfully running. So I am assuming that this is very specific to these latest macs as they don't use a traditional RAM instead they use Unified Memory.

@styxlab Please see if you have any idea about this issue.

**Comment by styxlab** [comment] 2021-05-27 10:16
Thanks for the additional info, unfortunately it does not give much more insight:
1. Missing SourceMaps is not a real issue, you may have to add source map generation in the ts config file so this warning goes away.
2. Error SIGSEGV is extremely generic, so no info here.
3. you cannot attach the debugger, because your program already crashed (no info here as well)

**Comment by styxlab** [comment] 2021-05-27 10:19
As the standard Next.js React example is working, maybe its a better idea to strip the project down as much as possible. A first step towards this goal could be to disable all features in `appCongig.ts` as follows:

```
export const fileCache: boolean = false

export const nextFeatureImages: boolean = false
export const nextInlineImages: boolean = false

export const rssFeed: boolean = false
export const memberSubscriptions: boolean = false

export const prism: boolean = false
export const contactPage: boolean = false

export const toc: boolean = false

export const isr: boolean = false
```

How does the app behave on your machine with these options?





```

**Comment by raihanameen** [comment] 2021-05-27 23:31
The application runs stable in the below configuration:

```
// Cache control
export const fileCache: boolean = false

// Dark mode
export type DarkMode = 'dark' | 'light' | null
export const defaultMode: DarkMode = 'light'
export const overrideOS: boolean = true

// Images
export const nextFeatureImages: boolean = false
export const nextInlineImages: boolean = true
export const imageQuality: number = 80
export const sourceImages: boolean = false

// RSS
export const rssFeed: boolean = true

// Ghost Member Subscriptions
export const memberSubscriptions: boolean = true

// Commenting system
export type CommentingSystem = 'commento' | 'disqus' | null
export const commenting: CommentingSystem = null

export const commentoUrl: string = 'https://cdn.commento.io' // 'https://commento.your-blog.com'
export const disqusShortname: string = 'short-name-here'

// PrismJS
export const prism: boolean = true
export const prismIgnoreMissing: boolean = true

// Contact Page
export const contactPage: boolean = true
export const customPage = {}

// Table of Contents
export const toc: boolean = true
export const maxDepth: number = 2

// Custom site navigation (default: [], label is case sensitive)
// Override: [{ label: 'Home', url: '/' }]
// Add new: [{ label: 'Contact', url: '/contact' }]
import { NavItem } from '@lib/ghost'
export const customNavigation: NavItem[] = [{ label: 'Contact', url: '/contact' }]

// Incremental Static Regenerations (ISR)
export const isr: boolean = true
export const maxNumberOfPosts: number = 20
export const maxNumberOfPages: number = 20

```
These were the things I came across today:

* Every link in the application is a bit of a hassle to get into as I am not able to open them with a normal click, I have to open by control+click (open in new tab).
* The problem seems to be with caching and images.
* The application was very slow in loading every page, but I think NextJS is usually slow in dev env and very fast in prod.

**Comment by raihanameen** [comment] 2021-05-28 08:05
1. Yes it works in other NextJS projects
2. It crashes in both cases.
3. Yea thanks, I tried it immediately after sending my previous message.

**Comment by styxlab** [comment] 2021-05-28 08:22
Original issue seems related to Node 16 on ARM: https://github.com/vercel/next.js/issues/24421

Can you test if it the workaround mentioned by Tim in that thread works:

> 
> This seems related to Node.js 16 being the first version compiled for M1 ARM. As a temporary workaround you can use the steps provided here: https://github.com/nvm-sh/nvm#macos-troubleshooting
> 
> nvm uninstall 16
> arch -x86_64 zsh
> nvm install 16
> exit
> 
> Then you'll have the x64 version of Node installed instead of the ARM version.

**Comment by raihanameen** [comment] 2021-05-28 08:29
Is there any better solution for this?

**Comment by styxlab** [comment] 2021-05-28 08:38
Probably not at the moment. You are living on the M1 edge...

**Comment by raihanameen** [comment] 2021-05-28 08:39
😅 So are you leaving this issue open?

**Comment by styxlab** [comment] 2021-05-28 08:43
No, I will close it as solved :rofl:

**Comment by raihanameen** [comment] 2021-05-28 08:44
😂👍🏻 fine thanks

**Comment by styxlab** [comment] 2021-05-28 08:47
More seriously, I think you have the following options

- run on a different machine (or maybe a VM with a different OS, not sure if that would be sufficient)
- live with the quirks (no image optimization, strange link behavior, etc.)
- switch Node to the x84 version (although it needs to be tested, if that solves everything)

Did I forget something?

**Comment by raihanameen** [comment] 2021-05-28 08:50
I chose to spin up a droplet in digitalocean and also tried it out in vercel.

**Comment by styxlab** [comment] 2021-05-28 08:51
Cool, so you know your way around. Will close the issue as I don't see I can add anything further.

**Comment by styxlab** [comment] 2021-05-28 08:53
Could you please change the title to something like "Running with Node 16 on ARM M1 causes SIGSEGV" or something similar, so it contains the important keywords?

**Comment by styxlab** [comment] 2021-05-28 08:55
Perfect, thanks so much for reporting and following up. I will add you to the contributor's list.

**Comment by styxlab** [comment] 2021-05-28 08:56
@all-contributors please add @raihanameen  for issue

**Closed by styxlab** 2021-05-28 08:55 UTC

**Comment by styxlab** [comment] 2021-05-28 08:58
@all-contributors please add @raihanameen  for bug
