### ISSUE TITLE
Tag pages do not load up

### ISSUE THREAD

**Issue by icy-meteor** [styxlab/next-cms-ghost#35] opened 2021-01-24 06:36 UTC
When I visit the tag pages, they do not open up. 
It just says "An unexpected error has occurred."

![image](https://user-images.githubusercontent.com/22114682/105623044-848fd700-5e3c-11eb-84ee-db299a736723.png)

Hosted version: https://next-cms-ghost-j2jwkzzdp.vercel.app/tag/developer-essentials
Original source: https://www.crio.do/blog/tag/developer-essentials/

**Comment by styxlab** [comment] 2021-01-24 10:01
You need to find the exact error message in the Vercel console and post it here for further assistance. My best guess is that you switched image optimizations on again (which is the recommended setting for Vercel deploys) but forgot to add the domains for image serving in `next.config.js`. For your site, I had to add at least the following:

```
      'www.crio.do',
      'drive.google.com',
      'lh3.googleusercontent.com',
      'lh6.googleusercontent.com',
```
But it could be something different. Just note that I am able to the tag page on localdomain:
![image](https://user-images.githubusercontent.com/19638263/105626905-7ee1c380-5e33-11eb-80ed-2932d77a0365.png)

**Comment by styxlab** [comment] 2021-01-26 20:19
As I cannot reproduce the issue (it works fine on my end) I am going to close it. If you want to reopen, please attach detailed error logs and some instructions on what you did to get there.

**Closed by styxlab** 2021-01-26 20:19 UTC
