### ISSUE TITLE
Deploy with vercel, click on an article and click on the logo in the upper left corner to jump to the domain name assigned by vercel instead of your own domain name.  netlify is normal

### ISSUE THREAD

**Issue by RhiMaker** [styxlab/next-cms-ghost#116] opened 2021-08-07 06:32 UTC
SITE_URL has been set
![20210807_142620](https://user-images.githubusercontent.com/2142431/128590831-26100dbc-3b4e-407c-80af-20c635abb823.gif)

**Comment by styxlab** [comment] 2021-08-24 09:18
Sorry for the long response time, the issue has been fixed, so that it works even without setting the `SITE_URL`. However, please note that you need to re-deploy your project after setting `SITE_URL` otherwise it is not correctly picked up. This was the root cause in your case, however, as `SITE_URL` is not really needed for navigating to the main page, the code has been simplified.

**Comment by styxlab** [comment] 2021-08-25 07:26
Closed as solved.

**Closed by styxlab** 2021-08-25 07:26 UTC
