### ISSUE TITLE
Error: Error: Validation (isSlug) failed for slug

### ISSUE THREAD

**Issue by simhol** [styxlab/next-cms-ghost#75] opened 2021-04-18 07:29 UTC
I've received this error on a fresh new project. Just cloned the starter and provided a .env.local file with the API_URL and _KEY to my Ghost instance.

I get the following error in my terminal when running this in my dev environment:

Error: Error: Validation (isSlug) failed for slug
    at getPostBySlug (F:\Projects\tsc-blog\.next\server\pages\index.js:4018:134)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getStaticProps (F:\Projects\tsc-blog\.next\server\pages\[...slug].js:10310:10)
    at async renderToHTML (F:\Projects\tsc-blog\node_modules\next\dist\next-server\server\render.js:28:1737)
    at async F:\Projects\tsc-blog\node_modules\next\dist\next-server\server\next-server.js:112:97
    at async __wrapper (F:\Projects\tsc-blog\node_modules\next\dist\lib\coalesced-function.js:1:330)
    at async DevServer.renderToHTMLWithComponents (F:\Projects\tsc-blog\node_modules\next\dist\next-server\server\next-server.js:137:387)
    at async DevServer.renderToHTML (F:\Projects\tsc-blog\node_modules\next\dist\next-server\server\next-server.js:138:923)
    at async DevServer.renderToHTML (F:\Projects\tsc-blog\node_modules\next\dist\server\next-dev-server.js:35:578)
    at async DevServer.render (F:\Projects\tsc-blog\node_modules\next\dist\next-server\server\next-server.js:75:236)
    at async Object.fn (F:\Projects\tsc-blog\node_modules\next\dist\next-server\server\next-server.js:59:580)
    at async Router.execute (F:\Projects\tsc-blog\node_modules\next\dist\next-server\server\router.js:25:67)
    at async DevServer.run (F:\Projects\tsc-blog\node_modules\next\dist\next-server\server\next-server.js:69:1042)
    at async DevServer.handleRequest (F:\Projects\tsc-blog\node_modules\next\dist\next-server\server\next-server.js:34:504)

I've changed nothing in the original repo.

**Comment by styxlab** [comment] 2021-04-18 09:35
@simhol Sorry to hear you are running into issues. This error is coming from your Ghost CMS (there is no `isSlug` function in this repo).

1. Please comment out  API_URL and _KEY in your ` .env.local`: In this case content is fetched from the example Ghost CMS. If this works, you know that the error is caused by your Ghost installation (see https://github.com/TryGhost/Ghost/issues/10525) or is related to your specific content.
2. Make sure your Ghost CMS is up-to-date (I am running a v4 instance, but a recent v3 should work too).
3. Try to start with a fresh installation, copy all images over and then export/import 1 post at a time (this is a crude way to isolate problems coming from specific content, but should only be done as a last resort if all other debugging fails). You could also unpublish posts / pages, if you think a post is making trouble.

I also notice that you are building on Windows which is not officially supported (it means you are a bit on your own when it comes to debugging). I recommend using WSL 2 with Ubuntu when building on Windows. However, I don't think this is the issue here.

**Comment by simhol** [comment] 2021-04-18 10:46
Hey @styxlab,

thanks again for taking yourtime with me, much appreciated.

When I run the repo in demo mode, I immediately get 

![image](https://user-images.githubusercontent.com/4987937/115142809-0eb69880-a044-11eb-8576-b9e395710ed0.png)

in my browser console and images don't show.

This is probably not related but an issue nonetheless :)

**Comment by simhol** [comment] 2021-04-18 10:47
I will try to unpublish posts or import/export them to identify the malicious content!

**Comment by simhol** [comment] 2021-04-18 11:22
> Hey @styxlab,
> 
> thanks again for taking yourtime with me, much appreciated.
> 
> When I run the repo in demo mode, I immediately get
> 
> ![image](https://user-images.githubusercontent.com/4987937/115142809-0eb69880-a044-11eb-8576-b9e395710ed0.png)
> 
> in my browser console and images don't show.
> 
> This is probably not related but an issue nonetheless :)

Ah this goes away if I set export const nextFeatureImages: boolean = false

**Comment by styxlab** [comment] 2021-04-18 11:56
Can you please open a new issue for this error as it looks unrelated?

**Comment by styxlab** [comment] 2021-04-18 11:59
> I will try to unpublish posts or import/export them to identify the malicious content!

Before doing that, please make sure your Ghost instance is running on a recent version. Please also publish your software versions for OS, Ghost and npm/yarn. You are getting many errors I have never seen before, so something is fundamentally wrong here.

**Comment by styxlab** [comment] 2021-04-19 08:08
@simhol: moved the image optimization issue to #76

**Comment by styxlab** [comment] 2021-05-01 09:00
Closing as not reproducable. If you disagree, please link to a repository with a reproducable example and add some instructions to it.

**Closed by styxlab** 2021-05-01 09:00 UTC
