### ISSUE TITLE
images.ts: Error while probing image with url:

### ISSUE THREAD

**Issue by VashAkame** [styxlab/next-cms-ghost#119] opened 2021-08-23 13:48 UTC
Error: ProbeError: bad status code: 404
    at imageDimensions (D:\Github\next-cms\.next\server\pages\404.js:3302:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async createNextImage (D:\Github\next-cms\.next\server\pages\404.js:3020:22)
    at async getAllSettings (D:\Github\next-cms\.next\server\pages\404.js:3081:21)
    at async getStaticProps (D:\Github\next-cms\.next\server\pages\404.js:6428:20)
    at async Object.renderToHTML (D:\Github\next-cms\node_modules\next\dist\server\render.js:374:24)
    at async doRender (D:\Github\next-cms\node_modules\next\dist\server\next-server.js:1127:38)
    at async D:\Github\next-cms\node_modules\next\dist\server\next-server.js:1221:28
    at async D:\Github\next-cms\node_modules\next\dist\server\response-cache.js:60:36

**Comment by VashAkame** [comment] 2021-08-23 13:48
![image](https://user-images.githubusercontent.com/64150468/130458585-4178c4ba-fc15-435e-9463-dae50b68c1f1.png)

**Comment by styxlab** [comment] 2021-08-23 15:39
Welcome @VashAkame! Sorry that you are having trouble compiling this project. To be able to help you, I usually need a link to a repo and some instructions on how to reproduce the issue.

As I can see this is image related, you should first try to switch off [image optimizations](https://github.com/styxlab/next-cms-ghost/blob/a801f59e067762f88a2c402c8a19a54084939c80/appConfig.ts#L15) in `appConfig.ts`:

```
// Images
export const nextFeatureImages: boolean = false
export const nextInlineImages: boolean = false
```

in order to isolate the issue. Let me know the outcome.

The most common error with regards to images is that the image domains are not properly specified. See the [README](https://github.com/styxlab/next-cms-ghost#-nextjs-image-optimizations), but am not sure if that is the issue here.

**Comment by styxlab** [comment] 2021-08-25 07:25
Closing as answered. Please let me know if you think the issue is not resolved.

**Closed by styxlab** 2021-08-25 07:25 UTC
